version: '3.4'

services:
  apigw-base:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:80
      - ASPNETCORE_HTTPS_PORT=44328
    ports:
      - "54232:80"
      - "44328:443"
  botflowgraph-identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:80
    ports:
      - "44330:443"
  botflowgraph-webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:80     
    ports:
      - "54231:80"
  botflowgraph-angular-client:
    ports:
      - "80:80"
  sqlserver:
    environment:
      - SA_PASSWORD="777888123456"
      - ACCEPT_EULA="Y"
    ports:
      - "1433:1433"  
  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
      - MONGO_INITDB_DATABASE=BotDb
    ports:
      - "27017:27017" 
  