version: '3.4'

services:
  apigw-base:
    image: ${DOCKER_REGISTRY-}apigwbase
    build:
      context: .
      dockerfile: src/ApiGateway/ApiGw-Base/Dockerfile
    depends_on:
        - botflowgraph-webapi
        - botflowgraph-identity
  botflowgraph-identity:
    image: ${DOCKER_REGISTRY-}botflowgraph.identity
    build:
      context: .
      dockerfile: src/Services/BotFlowGraph.Identity/Dockerfile
    depends_on:
        - sqlserver
  botflowgraph-webapi:
    image: ${DOCKER_REGISTRY-}botflowgraph.webapi
    build:
      context: .
      dockerfile: src/Services/BotFlowGraph.WebApi/Dockerfile
    depends_on:
        - mongo-db
  mongo-db:
    image: mongo:latest
  sqlserver:
    image: mcr.microsoft.com/mssql/server
  spa-clinet:
    image: ${DOCKER_REGISTRY-}angulardrawgraph_app.web  





